extends Node

signal muncul_panduan
signal ketemu
signal pick_tool
signal ganti_tool
signal misi1
signal dialooog
signal push_door
signal ganti_tangan
signal coin_collected
signal misi1selesai
signal reward1
signal pushdoor2
signal pushdoor3
signal raden_intan2
signal raden_intan3
signal hiden
signal hiden2
signal gariskuning
signal buku_diambil
signal di_oke
signal sudah_dapat_kamus
