extends Node

signal muncul_panduan
signal ketemu
signal pick_tool
signal ganti_tool
signal misi1
signal dialooog
signal push_door
signal ganti_tangan
signal coin_collected
signal misi1selesai
signal reward1
signal pushdoor2
signal pushdoor3
signal raden_intan2
signal raden_intan3
signal hiden
signal hiden2
signal gariskuning
signal buku_diambil
signal di_oke
signal sudah_dapat_kamus
signal bayangan_papan
signal muncul_buku
signal analog
signal tekan
signal misi_anter
signal anter_buah
signal terima_buah
signal terima_buah_selesai
signal muncul_sabit
signal bush_hilang
signal janganmuncul
signal pohon_pisang
signal pohon_pisang2
signal muncul_buah_pisang
signal lineout1
signal lineout2
signal cari_pisang
signal sinyal_npc_afnan
signal misipisang_ditemukan1
signal misipisang_ditemukan2
signal susi_false
signal bapakMC_muncul
signal misi2
signal misi3
signal misi4
signal misi5
signal dapetmisi2
signal dapetmisi4
signal ending
signal bpk_muncul
signal susi_muncul
